osx_image: xcode10.1
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild build -workspace Example/Pikko.xcworkspace -scheme Pikko-Example -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
